version: "2"

services:
  dnsresolver:
    build: .
    image: devopstest:0.1
    volumes:
      - ./src/dns_script.py:/etc/dns_script.py
      - ./domains.txt:/etc/domains.txt
    ports:
      - 80:80
