version: "2"

services:
  dnsresolver:
    image: groot:staging
    volumes:
      - ./dns_script.py:/etc/dns_script.py
      - ./domains.txt:/etc/domains.txt
    #command: "sleep 500"
    ports:
      - 80:80
