---
- hosts: localhost

  tasks:
    - name: run geoiplookup command
      shell: "geoiplookup {{ item }}"
      with_items: "{{domains}}"
      register: output

    - name: show command output
      shell: "echo {{item.0}} {{item.1}}"
      with_together:
        - "{{domains}}"
        - "{{ output.results | map(attribute='stdout_lines') | list }}"

  vars:
    domains: "{{ lookup('file', '../../domains.txt').splitlines() }}"
